import { SimplePool, getPublicKey } from 'https://esm.sh/nostr-tools@2.17.0';
const RELAYS=['wss://nos.lol','wss://relay.primal.net']; const pool=new SimplePool(); const $=s=>document.querySelector(s); const fromHex=hex=>new Uint8Array((hex.match(/.{1,2}/g)||[]).map(b=>parseInt(b,16))); const short=pk=>`${pk.slice(0,8)}…${pk.slice(-6)}`; const fmt=ts=>new Date(ts*1000).toLocaleString('ja-JP'); const tag=(ev,k)=>ev.tags?.find(t=>t[0]===k)?.[1];
function currentIdentity(){const hex=localStorage.getItem('boyaki-device-sk');if(!hex)return null;try{return{pk:getPublicKey(fromHex(hex))}}catch{return null}}
function setText(id,v){const n=$(id);if(n)n.textContent=String(v)}
function row(label,ev){const p=document.createElement('p');p.className='hint';const text=(ev.content||'').trim();p.textContent=`${label} · ${fmt(ev.created_at)}${text?` · ${text.slice(0,120)}`:''}`;return p}
function counter(ev,name){return tag(ev,'boyaki_counter')===name||tag(ev,'counter')===name}
async function profile(id){const local={displayName:localStorage.getItem('boyaki-profile-display-name')||localStorage.getItem('boyaki-maker-display-name')||'',about:localStorage.getItem('boyaki-profile-about')||''};let remote=null;try{const rows=await pool.querySync(RELAYS,{kinds:[0],authors:[id.pk],limit:20});const latest=rows.sort((a,b)=>b.created_at-a.created_at)[0];if(latest){const p=JSON.parse(latest.content||'{}');if(p.boyaki_schema==='profile-v1')remote=p}}catch{}return{displayName:remote?.display_name||remote?.name||local.displayName,about:remote?.about||local.about}}
async function evidence(id){const since=Math.floor(Date.now()/1000)-31536000;const rows=await pool.querySync(RELAYS,{authors:[id.pk],kinds:[1,5,7,1984,30023],since,limit:1000});const xs=[...new Map(rows.map(x=>[x.id,x])).values()].sort((a,b)=>b.created_at-a.created_at);const raw=xs.filter(e=>e.kind===1&&tag(e,'t')==='boyaki-raw'),vv=xs.filter(e=>counter(e,'voice-validation')),vr=xs.filter(e=>counter(e,'voice-resolved')||counter(e,'voice-improved')),ms=xs.filter(e=>counter(e,'maker-solution')),mr=xs.filter(e=>counter(e,'maker-release')),mv=xs.filter(e=>counter(e,'maker-validation')),mo=xs.filter(e=>counter(e,'maker-outcome'));setText('#voice-boyaki',raw.length);setText('#voice-validations',vv.length);setText('#voice-resolved',vr.length);setText('#maker-solutions',ms.length);setText('#maker-releases',mr.length);setText('#maker-validations',mv.length);setText('#maker-outcomes',mo.length);const vh=$('#voice-history');[...raw,...vv,...vr].sort((a,b)=>b.created_at-a.created_at).slice(0,8).forEach(e=>vh.append(row('Voice evidence',e)));if(!vh.children.length)vh.innerHTML='<p class="hint">まだVoiceのcanonical evidenceはありません。</p>';const mh=$('#maker-history');[...ms,...mr,...mv,...mo].sort((a,b)=>b.created_at-a.created_at).slice(0,8).forEach(e=>mh.append(row('Maker evidence',e)));if(!mh.children.length)mh.innerHTML='<p class="hint">まだMakerのcanonical evidenceはありません。</p>';const recent=$('#recent-history');xs.slice(0,12).forEach(e=>recent.append(row(tag(e,'role')||tag(e,'t')||`kind-${e.kind}`,e)));if(!recent.children.length)recent.innerHTML='<p class="hint">このブラウザIDに紐づく最近の活動はありません。</p>'}
async function main(){const id=currentIdentity();if(!id){$('#profile-state').textContent='このブラウザにはBOYAKI IDがまだありません。新規登録すると現在のブラウザにIDが作られます。';$('#profile-name').textContent='未登録';$('#device-id').textContent='not created';$('#profile-actions').innerHTML='<a class="button-link" href="./register.html">新規登録へ</a>';return}$('#device-id').textContent=short(id.pk);const p=await profile(id);if(p.displayName){$('#profile-name').textContent=p.displayName;$('#profile-about').textContent=p.about||'';$('#profile-state').textContent='現在のブラウザIDを自動認識しました。';$('#profile-actions').innerHTML='<a class="button-link" href="./register.html">プロフィールを編集</a>'}else{$('#profile-name').textContent='プロフィール未登録';$('#profile-state').textContent='ブラウザIDはありますが、プロフィールはまだ登録されていません。匿名利用はそのまま可能です。';$('#profile-actions').innerHTML='<a class="button-link" href="./register.html">プロフィールを作る</a>'}try{await evidence(id)}catch{$('#recent-history').innerHTML='<p class="hint">活動データを取得できませんでした。通信状態を確認して再読み込みしてください。</p>'}}
main();
