import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
import vm from 'node:vm';
const root=new URL('../',import.meta.url);
const read=p=>readFile(new URL(p,root),'utf8');
function storage(seed={}){
 const value={...seed};Object.defineProperties(value,{getItem:{value:k=>value[k]??null},setItem:{value:(k,v)=>value[k]=String(v)},removeItem:{value:k=>delete value[k]}});return value;
}
const local=storage({'boyaki-account-sk':'STAGING sentinel','boyaki-device-sk':'STAGING device','boyaki-profile-display-name':'STAGING profile'}),session=storage({'boyaki-account-sk':'STAGING session'}),calls=[];
class XHR{open(method,url){calls.push({method,url})}addEventListener(){}}
const context={URL,Request,XMLHttpRequest:XHR,location:{origin:'https://camembert1001.github.io',href:'https://camembert1001.github.io/boyaki-public/ai-staging/'},document:{documentElement:{dataset:{}},readyState:'loading',addEventListener(){}},navigator:{sendBeacon:()=>true},window:{localStorage:local,sessionStorage:session,fetch:async(url)=>{calls.push(url);return{status:200}}}};
vm.runInNewContext(await read('ai-environment.js'),context);
const s=context.window.BOYAKI_STORAGE;
s.local.setItem('boyaki-account-sk','AI sentinel');s.session.setItem('boyaki-account-sk','AI session');
assert.equal(local['boyaki-account-sk'],'STAGING sentinel');assert.equal(session['boyaki-account-sk'],'STAGING session');assert.equal(local['ai-staging:boyaki:boyaki-account-sk'],'AI sentinel');
s.local.clear();s.session.clear();assert.equal(local['boyaki-device-sk'],'STAGING device');assert.equal(local['boyaki-account-sk'],'STAGING sentinel');assert.equal(session['boyaki-account-sk'],'STAGING session');
const base='https://vbqitqjhobzpdlaraglc.supabase.co/functions/v1/';
for(const target of [base+'boyaki-api/posts',base+'boyaki-api/account-credentials',base+'boyaki-thread-api/posts','https://uvjyponltgoytjzwkfrh.supabase.co/functions/v1/boyaki-api/posts','https://camembert1001.github.io/boyaki-public/staging/index.html','https://camembert1001.github.io/boyaki-public/ai-staging/../staging/index.html',base+'ai-staging-boyaki-api-malicious/posts'])await assert.rejects(()=>context.window.fetch(target),/network_boundary/);
assert.equal(calls.length,0);
await context.window.fetch(base+'boyaki-api/account-credentials/resolve?login_key_hash='+'a'.repeat(64));assert.equal(calls.length,1);
await context.window.fetch(base+'ai-staging-boyaki-api/health');assert.equal(calls.length,2);await context.window.fetch(base+'ai-staging-commerce-api/health');assert.equal(calls.length,3);await context.window.fetch(base+'ai-staging-inbox-api/health');assert.equal(calls.length,4);
assert.throws(()=>new context.window.WebSocket('wss://example.com'),/relay_disabled/);
const events={},deleted=[],cached=[];let pending;
vm.runInNewContext(await read('sw.js'),{URL,Response,self:{location:{href:context.location.href+'sw.js'},addEventListener:(n,f)=>events[n]=f,clients:{claim:async()=>{}},skipWaiting:async()=>{}},caches:{keys:async()=>['boyaki-shell-v8','production-cache','ai-staging:boyaki:shell:old'],delete:async k=>deleted.push(k),open:async k=>({addAll:async a=>cached.push({k,a})})}});
events.activate({waitUntil:p=>pending=p});await pending;assert.deepEqual(deleted,['ai-staging:boyaki:shell:old']);
events.install({waitUntil:p=>pending=p});await pending;assert(cached.every(x=>x.k.startsWith('ai-staging:boyaki:')&&x.a.every(u=>u.startsWith(context.location.href))));
let intercepted=false;for(const url of [base+'ai-staging-boyaki-api/posts','https://camembert1001.github.io/boyaki-public/staging/index.html'])events.fetch({request:{method:'GET',url},respondWith:()=>intercepted=true});assert.equal(intercepted,false);
async function walk(dir=''){let files=[];for(const x of await readdir(new URL(dir||'.',root),{withFileTypes:true})){if(x.name==='tests'||x.name==='supabase')continue;const p=dir+x.name;if(x.isDirectory())files.push(...await walk(p+'/'));else files.push(p)}return files}
const files=await walk();for(const file of files.filter(f=>/\.(js|html)$/.test(f))){const text=await read(file),identityStripped=text.replaceAll('functions/v1/boyaki-api/account-credentials/resolve','');assert(!/functions\/v1\/boyaki|\/staging\/|wss:\/\//.test(identityStripped),file+' forbidden route');if(!['ai-environment.js','dev/e2e-selftest.js'].includes(file))assert(!/\b(?:localStorage|sessionStorage)\b/.test(text),file+' unscoped storage');if(file.endsWith('.html')&&text.includes('<html')){assert(text.includes('ai-environment.js'),file+' missing environment');assert(text.includes('Content-Security-Policy'),file+' missing CSP');for(const match of text.matchAll(/(?:src|href)="([^"?#]+)(?:\?[^"#]*)?"/g)){const ref=match[1];if(ref.startsWith('./')||ref.startsWith('../')){if(!ref.endsWith('/'))await readFile(new URL(ref,new URL(file,root))).catch(()=>{throw Error(file+' missing asset '+ref)})}}}}
const solutionRoomSource=await read('solution-room.js');
assert(!/SimplePool|RELAYS|pool\.publish|querySync|subscribeMany/.test(solutionRoomSource),'Solution Room must not use public relay transport');
assert(solutionRoomSource.includes('client.listSolutionRoomMessages(room)'),'Solution Room isolated read missing');
assert(solutionRoomSource.includes('client.createSolutionRoomMessage(room,message)'),'Solution Room isolated write missing');
assert(solutionRoomSource.includes('client.deleteSolutionRoomMessage(message.id)'),'Solution Room isolated delete missing');
const threadApiSource=await read('supabase/functions/ai-staging-boyaki-thread-api/index.ts');
assert(threadApiSource.includes("T('boyaki_solution_room_messages')"),'Solution Room backend table missing');
assert(threadApiSource.includes("T('boyaki_solution_rooms')"),'post-bound Solution Room table missing');
assert(threadApiSource.includes("T('boyaki_solution_cases')"),'Solution Case table missing');
assert(!threadApiSource.includes("db.from('boyaki_solution_room_messages')"),'Solution Room must stay under AI-STAGING table prefix');
assert(!threadApiSource.includes("db.from('boyaki_solution_rooms')"),'Solution Room registry must stay under AI-STAGING table prefix');
assert(!threadApiSource.includes("db.from('boyaki_solution_cases')"),'Solution Cases must stay under AI-STAGING table prefix');
const cutoverSource=await read('canonical-cutover.js');
const threadUiSource=await read('thread-ui.js');
assert(cutoverSource.includes("from './thread-ui.js?v=20260920-consolidated-v2'"),'thread UI module wiring missing');
assert(threadUiSource.includes('client.ensureSolutionRoom(post.id)'),'Thread -> Solution Room transition missing');
const caseCreateSource=await read('solution-case-create.js');
assert(caseCreateSource.includes('client.createSolutionCase(room,title,contribution)'),'Solution Case canonical write missing');
assert(!caseCreateSource.includes('boyaki-maker-solution-cases-v1'),'Solution Case must not fall back to browser-only history');
const historySource=await read('maker-contribution-history.js');
assert(historySource.includes('client.listMySolutionCases()'),'Account-scoped Contribution History read missing');
assert(!historySource.includes('boyaki-maker-solution-cases-v1'),'Contribution History must not use browser-only store');
const demandApiSource=await read('supabase/functions/ai-staging-boyaki-api/index.ts');
assert(demandApiSource.includes("T('boyaki_demand_signals')"),'demand signal AI table missing');
assert(!demandApiSource.includes("db.from('boyaki_demand_signals')"),'demand signals must stay under AI-STAGING table prefix');
const demandUiSource=await read('demand-ui.js');
assert(cutoverSource.includes("from './demand-ui.js?v=20260920-consolidated-v2'"),'demand UI module wiring missing');
assert(demandUiSource.includes('client.saveDemand(post.id'),'demand evidence write UI missing');
assert(demandUiSource.includes('購入予約や決済ではなく'),'demand evidence must distinguish reaction from purchase');
assert(demandUiSource.includes('source_author'),'source-author exclusion UI path missing');
const roomEvidenceSource=await read('solution-room.js');
assert(roomEvidenceSource.includes('renderDemandEvidence'),'Solution Room demand evidence UI missing');
const makerEvidenceSource=await read('maker-contribution-history.js');
assert(makerEvidenceSource.includes('evidence_snapshot'),'Maker history evidence snapshot rendering missing');
const threadEvidenceSource=await read('supabase/functions/ai-staging-boyaki-thread-api/index.ts');
assert(threadEvidenceSource.includes('evidence_snapshot'),'Solution Case evidence snapshot backend missing');
assert(threadEvidenceSource.includes('demandEvidenceForPost'),'Solution Room live demand evidence backend missing');
const contributionSource=await read('voice-contribution-history.js');
assert(contributionSource.includes('client.listMyVoiceHistory()'),'Voice Contribution History canonical read missing');
assert(threadUiSource.includes('participant_role:selectedRole'),'thread participant role persistence missing');
const threadHistorySource=await read('supabase/functions/ai-staging-boyaki-thread-api/index.ts');
assert(threadHistorySource.includes("path==='/me/voice-history'"),'Voice history endpoint missing');
assert(threadHistorySource.includes(".eq('participant_role','voice')"),'Voice history role filter missing');
const invitationThreadSource=await read('supabase/functions/ai-staging-boyaki-thread-api/index.ts');
assert(invitationThreadSource.includes("T('boyaki_solution_room_invitations')"),'Solution Room invitation table missing');
assert(invitationThreadSource.includes("T('boyaki_problem_statements')"),'shared Problem table missing');
assert(!invitationThreadSource.includes("db.from('boyaki_problem_statements')"),'shared Problems must stay under AI-STAGING prefix');
assert(invitationThreadSource.includes('shared_problem_required'),'Solution Case must be blocked before source-owner consent');
assert(invitationThreadSource.includes("invitee_context:'source_owner'"),'source-owner invitation context missing');
assert(invitationThreadSource.includes('shared_problem_consent_required'),'explicit shared Problem consent gate missing');
assert(invitationThreadSource.includes('source_owner_consent_required'),'non-owner must not create the first shared Problem');
assert(invitationThreadSource.includes('room_invitation_required'),'Room write gate missing');
assert(invitationThreadSource.includes('maker_role_required'),'Maker-only Room creation gate missing');
assert(threadUiSource.includes('inviteVoiceToSolutionRoom'),'Thread -> Voice invitation UI missing');
assert(threadUiSource.includes('acceptSolutionRoomInvitation'),'Voice invitation acceptance UI missing');
assert(threadUiSource.includes('listPostProducts(post.id)'),'Thread Product publish-back rendering missing');
assert(threadUiSource.includes('inviteSourceOwnerToSolutionRoom'),'Maker -> original Voice transition invitation UI missing');
assert(threadUiSource.includes('confirm_shared_problem'),'shared Problem consent payload missing');
assert(threadUiSource.includes('元のBOYAKI本文は後から取り下げられます'),'source-owner consent copy missing');
assert(cutoverSource.includes('元のBOYAKI文を取り下げる'),'post-consent withdrawal UI missing');
const onboardingSource=await read('onboarding.js');
assert(onboardingSource.includes('困りごとから、解決とProductが生まれる場所。'),'full BOYAKI lifecycle onboarding missing');
assert(onboardingSource.includes('みんなで解く困りごと'),'human-facing shared-problem explanation missing');
assert(onboardingSource.includes('消せるもの / 残るもの'),'withdrawal boundary onboarding missing');
assert(onboardingSource.includes('全部覚える必要はありません'),'progressive onboarding principle missing');
assert(threadUiSource.includes("journeyGuide(access.problem_statement?'solution':'thread')"),'Thread journey guide missing');
assert(threadUiSource.includes('この困りごとで、どちらの立場から関わるかを選びます'),'Voice/Maker contextual role explanation missing');
assert(threadUiSource.includes('あなたのBOYAKIと、みんなで残す困りごとをここで分けます'),'shared Problem transition micro-onboarding missing');
const solutionRoomHtml=await read('solution-room.html');
assert(solutionRoomHtml.includes('今いる段階：一緒に解決'),'Solution Room stage explanation missing');
const productCreateHtml=await read('product-create.html');
assert(productCreateHtml.includes('この時点では元の困りごとには掲載されません'),'Product creation/publish-back distinction missing');
assert(productCreateHtml.includes('Productを作成'),'Product creation CTA missing');
const productHtml=await read('product.html');
assert(productHtml.includes('このProductを元の困りごとに掲載する'),'Product publish-back Human UX missing');
const humanUxGuide=await read('HUMAN_UX.md');
assert(humanUxGuide.includes('ボヤく → 話し合う → 一緒に解決 → Product'),'Human UX vocabulary SSOT missing journey');
for(const legacy of ['maker-space.js','solution-candidates.json','thread-room-v1.js','open-thread-nav-v1.js','public-surface-suppression.js','public-surface-suppressions.json','external-attestation.js','relays.js','discover/train-ticketing.html','discover/work-admin.html','discover/discovery-post.js','legacy-write-freeze.js','e2e-selftest.html','e2e-selftest.js','ui-dom-selftest.html','ui-dom-selftest.js']){
  await assert.rejects(()=>read(legacy),/ENOENT/,legacy+' should be removed from active AI-STAGING');
}
await read('dev/e2e-selftest.html');
await read('dev/e2e-selftest.js');
await read('dev/ui-dom-selftest.html');
await read('dev/ui-dom-selftest.js');
const visibleSurfaceText=[
  await read('index.html'),await read('mypage.html'),await read('mypage.js'),await read('makers.html'),
  await read('solution-room.html'),await read('solution-room.js'),await read('solution-case-create.html'),
  await read('product.html'),await read('product-create.html'),await read('products.html'),
  await read('discover/index.html'),await read('onboarding.js'),await read('action-inbox.js'),
  await read('thread-ui.js'),await read('demand-ui.js'),await read('chat-first-v53.js'),await read('quality-index-gate.js')
].join('\n');
for(const jargon of ['Problem Market','Action Inbox','Shared Problem','Solution Room','Solution Case','Solution Log','Maker Space','BOYAKI canonical','E2E診断','Nostr Relay','解決候補として公開する']){
  assert(!visibleSurfaceText.includes(jargon),'human-facing jargon leaked: '+jargon);
}
const homeSource=await read('index.html');
assert(homeSource.includes('context-gate.js?v=20260920-consolidated-v2'),'context gate must be an explicit module asset');
assert(!homeSource.includes('BOYAKI_CONTEXT_GATE_VERSION'),'context gate must not remain as a large inline script');
assert(!homeSource.includes('train-ticketing')&&!homeSource.includes('work-admin'),'obsolete acquisition overlays must stay removed');
const commerceSource=await read('supabase/functions/ai-staging-commerce-api/index.ts');
assert(commerceSource.includes("T('boyaki_products')"),'AI-STAGING Product table missing');
assert(commerceSource.includes("T('boyaki_orders')"),'AI-STAGING Order table missing');
assert(commerceSource.includes("T('boyaki_entitlements')"),'AI-STAGING Entitlement table missing');
assert(commerceSource.includes("T('boyaki_product_thread_publications')"),'Product publish-back table missing');
assert(commerceSource.includes('source_thread_not_available'),'publish-back must stay bound to a live original/shared Problem thread');
assert(!commerceSource.includes("db.from('boyaki_products')"),'Products must stay under AI-STAGING prefix');
assert(!commerceSource.includes("db.from('boyaki_orders')"),'Orders must stay under AI-STAGING prefix');
assert(!commerceSource.includes("db.from('boyaki_entitlements')"),'Entitlements must stay under AI-STAGING prefix');
assert(commerceSource.includes("payment_provider:'ai_staging_test'"),'test payment provider marker missing');
assert(commerceSource.includes("real_payment_processed:false"),'no-real-payment marker missing');
const productUi=await read('product.js');
assert(productUi.includes('client.purchaseProduct(id)'),'Voice purchase UI missing');
assert(productUi.includes('client.accessProduct(id)'),'entitlement delivery UI missing');
assert(productUi.includes('実際の決済は発生していません'),'test checkout disclosure missing');
assert(!/stripe|paypal|paypay/i.test(productUi),'AI-STAGING commerce must not call real payment providers');
const productCreateUi=await read('product-create.js');
assert(productCreateUi.includes('client.createProduct'),'Case -> Product publish UI missing');
const makerCommerceUi=await read('maker-contribution-history.js');
assert(makerCommerceUi.includes('product-create.html?case='),'Solution Case -> Product transition missing');
const inboxApiSource=await read('supabase/functions/ai-staging-inbox-api/index.ts');
assert(inboxApiSource.includes("path==='/me/inbox'"),'Action Inbox endpoint missing');
assert(inboxApiSource.includes("path==='/me/inbox/seen'"),'Action Inbox seen endpoint missing');
assert(inboxApiSource.includes("T('boyaki_inbox_seen')"),'Action Inbox seen table missing');
assert(!inboxApiSource.includes("db.from('boyaki_inbox_seen')"),'Action Inbox state must stay under AI-STAGING prefix');
assert(inboxApiSource.includes("kind:'room_invitation'"),'Voice invitation Action Inbox item missing');
assert(inboxApiSource.includes("kind:'product_ready'"),'Voice Product-ready Action Inbox item missing');
assert(inboxApiSource.includes("kind:'purchase_ready'"),'Voice purchased Product Action Inbox item missing');
assert(inboxApiSource.includes("kind:'productize_case'"),'Maker Case -> Product Action Inbox item missing');
assert(inboxApiSource.includes("kind:'publish_product'"),'Maker Product publish-back Action Inbox item missing');
assert(inboxApiSource.includes("kind:'room_activity'"),'Solution Room activity Inbox item missing');
assert(inboxApiSource.includes("kind:'sale'"),'Maker sale Inbox update missing');
assert(inboxApiSource.includes("kind:'market_opportunity'"),'Maker unresolved-demand Inbox opportunity missing');
assert(!/notifications|notification_payload/.test(inboxApiSource),'Inbox must derive actions rather than persist notification copies');
const inboxUiSource=await read('action-inbox.js');
assert(inboxUiSource.includes('client.listMyInbox()'),'Action Inbox client read missing');
assert(inboxUiSource.includes('client.markInboxSeen'),'Action Inbox seen marker UI missing');
assert(inboxUiSource.includes("item.priority!=='action'"),'Action-required items must remain visible until resolved');
const myPageSource=await read('mypage.html');
assert(myPageSource.includes('data-mypage-tab="inbox"'),'My Page Inbox tab missing');
assert(myPageSource.includes('data-action-inbox'),'My Page Action Inbox mount missing');
const apiSource=await read('supabase/functions/ai-staging-boyaki-api/index.ts');
assert(apiSource.includes("db.from('boyaki_accounts').select('account_pubkey')"),'shared identity read missing');
assert(!/db\.from\('boyaki_accounts'\)\.(?:insert|upsert|update|delete)/.test(apiSource),'AI-STAGING must never mutate shared identity');
assert(apiSource.includes("activity_scope:'AI-STAGING'"),'activity scope marker missing');
assert(apiSource.includes("T('boyaki_problem_statements')"),'BOYAKI API shared Problem lookup missing');
assert(!apiSource.includes("db.from('boyaki_problem_statements')"),'BOYAKI Problem lifecycle must stay under AI-STAGING prefix');
assert(apiSource.includes("status:'withdrawn'"),'personal BOYAKI withdrawal state missing');
assert(apiSource.includes("thread_preserved:true"),'post-consent Thread preservation missing');
assert(apiSource.includes("thread_preserved:false"),'pre-consent full deletion path missing');
assert(apiSource.includes("p==='/problems'"),'first-class shared Problem market endpoint missing');
assert(apiSource.includes("market_scope:'shared_problem_only'"),'Problem market must exclude casual BOYAKI');
const marketUi=await read('discover/problem-market.js');
assert(marketUi.includes('client.listProblems(200)'),'Problem Market canonical problem read missing');
assert(marketUi.includes('client.listProducts()'),'Problem Market Product shelf join missing');
assert(marketUi.includes("state.filter==='pay'"),'Problem Market demand filter missing');
assert(marketUi.includes("state.sort==='demand'"),'Problem Market demand sorting missing');
const marketHtml=await read('discover/index.html');
assert(marketHtml.includes('解決する問題を探す'),'problem discovery surface missing');
assert(marketHtml.includes('みんなで解く困りごと'),'shared-problem boundary explanation missing');
assert(commerceSource.includes("T('boyaki_problem_statements')"),'commerce shared Problem source lookup missing');
console.log(JSON.stringify({ok:true,checks:['local/session sentinel preserved including clear','normal APIs blocked except exact read-only shared identity resolver','Production API and path traversal denied before transport','public WebSockets blocked','worker cleanup limited to AI prefix','worker ignores API and other environments','all live HTML has early boundary and CSP','all application storage scoped','AI backend may read shared identity but cannot mutate it','AI activity remains explicitly scoped to AI-STAGING','Solution Room uses isolated API rather than public relays','Solution Room storage stays under ai_staging_*','Thread -> Room transition is canonical','Solution Cases are account-scoped and not browser-only','Demand Evidence stays under ai_staging_* and is not framed as purchase','Voice role is persisted and Voice history is account-scoped','Solution Cases freeze demand evidence while Rooms show live evidence','Product -> Order -> Entitlement commerce stays AI-STAGING-only with test payment','Thread -> invite -> Room -> Product publish-back is source-bound','Casual BOYAKI stays deletable until original Voice explicitly creates a shared Problem','After consent original text can withdraw while Problem/Demand/Solution/Product remain','Shared Problems have a dedicated demand/Product discovery market','Voice/Maker Action Inbox derives next work from current domain state','Inbox persists only lightweight seen markers, not notification copies','Human onboarding explains the complete BOYAKI lifecycle without blocking casual posting','Thread/Room/Product surfaces show contextual journey stage and transition meaning','Human UX vocabulary is constrained by HUMAN_UX.md','demand and thread UI are split out of the feed/publication controller','home has no obsolete acquisition or compatibility overlays','developer diagnostics are isolated under dev/','inactive legacy surfaces are removed from active AI-STAGING','relative assets exist'],files:files.length},null,2));
