import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
import vm from 'node:vm';
const root=new URL('../',import.meta.url);
const read=p=>readFile(new URL(p,root),'utf8');
function storage(seed={}){
 const value={...seed};Object.defineProperties(value,{getItem:{value:k=>value[k]??null},setItem:{value:(k,v)=>value[k]=String(v)},removeItem:{value:k=>delete value[k]}});return value;
}
const local=storage({'boyaki-account-sk':'STAGING sentinel','boyaki-device-sk':'STAGING device','boyaki-profile-display-name':'STAGING profile'}),session=storage({'boyaki-account-sk':'STAGING session'}),calls=[];
class XHR{open(method,url){calls.push({method,url})}addEventListener(){}}
const context={URL,Request,XMLHttpRequest:XHR,location:{origin:'https://camembert1001.github.io',href:'https://camembert1001.github.io/boyaki-public/ai-staging/'},document:{documentElement:{dataset:{}},readyState:'loading',addEventListener(){}},navigator:{sendBeacon:()=>true},window:{localStorage:local,sessionStorage:session,fetch:async(url)=>{calls.push(url);return{status:200}}}};
vm.runInNewContext(await read('ai-environment.js'),context);
const s=context.window.BOYAKI_STORAGE;
s.local.setItem('boyaki-account-sk','AI sentinel');s.session.setItem('boyaki-account-sk','AI session');
assert.equal(local['boyaki-account-sk'],'STAGING sentinel');assert.equal(session['boyaki-account-sk'],'STAGING session');assert.equal(local['ai-staging:boyaki:boyaki-account-sk'],'AI sentinel');
s.local.clear();s.session.clear();assert.equal(local['boyaki-device-sk'],'STAGING device');assert.equal(local['boyaki-account-sk'],'STAGING sentinel');assert.equal(session['boyaki-account-sk'],'STAGING session');
const base='https://vbqitqjhobzpdlaraglc.supabase.co/functions/v1/';
for(const target of [base+'boyaki-api/posts',base+'boyaki-api/account-credentials',base+'boyaki-thread-api/posts','https://uvjyponltgoytjzwkfrh.supabase.co/functions/v1/boyaki-api/posts','https://camembert1001.github.io/boyaki-public/staging/index.html','https://camembert1001.github.io/boyaki-public/ai-staging/../staging/index.html',base+'ai-staging-boyaki-api-malicious/posts'])await assert.rejects(()=>context.window.fetch(target),/network_boundary/);
assert.equal(calls.length,0);
await context.window.fetch(base+'boyaki-api/account-credentials/resolve?login_key_hash='+'a'.repeat(64));assert.equal(calls.length,1);
await context.window.fetch(base+'ai-staging-boyaki-api/health');assert.equal(calls.length,2);
assert.throws(()=>new context.window.WebSocket('wss://example.com'),/relay_disabled/);
const events={},deleted=[],cached=[];let pending;
vm.runInNewContext(await read('sw.js'),{URL,Response,self:{location:{href:context.location.href+'sw.js'},addEventListener:(n,f)=>events[n]=f,clients:{claim:async()=>{}},skipWaiting:async()=>{}},caches:{keys:async()=>['boyaki-shell-v8','production-cache','ai-staging:boyaki:shell:old'],delete:async k=>deleted.push(k),open:async k=>({addAll:async a=>cached.push({k,a})})}});
events.activate({waitUntil:p=>pending=p});await pending;assert.deepEqual(deleted,['ai-staging:boyaki:shell:old']);
events.install({waitUntil:p=>pending=p});await pending;assert(cached.every(x=>x.k.startsWith('ai-staging:boyaki:')&&x.a.every(u=>u.startsWith(context.location.href))));
let intercepted=false;for(const url of [base+'ai-staging-boyaki-api/posts','https://camembert1001.github.io/boyaki-public/staging/index.html'])events.fetch({request:{method:'GET',url},respondWith:()=>intercepted=true});assert.equal(intercepted,false);
async function walk(dir=''){let files=[];for(const x of await readdir(new URL(dir||'.',root),{withFileTypes:true})){if(x.name==='tests'||x.name==='supabase')continue;const p=dir+x.name;if(x.isDirectory())files.push(...await walk(p+'/'));else files.push(p)}return files}
const files=await walk();for(const file of files.filter(f=>/\.(js|html)$/.test(f))){const text=await read(file),identityStripped=text.replaceAll('functions/v1/boyaki-api/account-credentials/resolve','');assert(!/functions\/v1\/boyaki|\/staging\/|wss:\/\//.test(identityStripped),file+' forbidden route');if(!['ai-environment.js','e2e-selftest.js'].includes(file))assert(!/\b(?:localStorage|sessionStorage)\b/.test(text),file+' unscoped storage');if(file.endsWith('.html')&&text.includes('<html')){assert(text.includes('ai-environment.js'),file+' missing environment');assert(text.includes('Content-Security-Policy'),file+' missing CSP');for(const match of text.matchAll(/(?:src|href)="([^"?#]+)(?:\?[^"#]*)?"/g)){const ref=match[1];if(ref.startsWith('./')||ref.startsWith('../')){if(!ref.endsWith('/'))await readFile(new URL(ref,new URL(file,root))).catch(()=>{throw Error(file+' missing asset '+ref)})}}}}
const solutionRoomSource=await read('solution-room.js');
assert(!/SimplePool|RELAYS|pool\.publish|querySync|subscribeMany/.test(solutionRoomSource),'Solution Room must not use public relay transport');
assert(solutionRoomSource.includes('client.listSolutionRoomMessages(room)'),'Solution Room isolated read missing');
assert(solutionRoomSource.includes('client.createSolutionRoomMessage(room,message)'),'Solution Room isolated write missing');
assert(solutionRoomSource.includes('client.deleteSolutionRoomMessage(message.id)'),'Solution Room isolated delete missing');
const threadApiSource=await read('supabase/functions/ai-staging-boyaki-thread-api/index.ts');
assert(threadApiSource.includes("T('boyaki_solution_room_messages')"),'Solution Room backend table missing');
assert(threadApiSource.includes("T('boyaki_solution_rooms')"),'post-bound Solution Room table missing');
assert(threadApiSource.includes("T('boyaki_solution_cases')"),'Solution Case table missing');
assert(!threadApiSource.includes("db.from('boyaki_solution_room_messages')"),'Solution Room must stay under AI-STAGING table prefix');
assert(!threadApiSource.includes("db.from('boyaki_solution_rooms')"),'Solution Room registry must stay under AI-STAGING table prefix');
assert(!threadApiSource.includes("db.from('boyaki_solution_cases')"),'Solution Cases must stay under AI-STAGING table prefix');
const cutoverSource=await read('canonical-cutover.js');
assert(cutoverSource.includes('client.ensureSolutionRoom(post.id)'),'Thread -> Solution Room transition missing');
const caseCreateSource=await read('solution-case-create.js');
assert(caseCreateSource.includes('client.createSolutionCase(room,title,contribution)'),'Solution Case canonical write missing');
assert(!caseCreateSource.includes('boyaki-maker-solution-cases-v1'),'Solution Case must not fall back to browser-only history');
const historySource=await read('maker-contribution-history.js');
assert(historySource.includes('client.listMySolutionCases()'),'Account-scoped Contribution History read missing');
assert(!historySource.includes('boyaki-maker-solution-cases-v1'),'Contribution History must not use browser-only store');
const demandApiSource=await read('supabase/functions/ai-staging-boyaki-api/index.ts');
assert(demandApiSource.includes("T('boyaki_demand_signals')"),'demand signal AI table missing');
assert(!demandApiSource.includes("db.from('boyaki_demand_signals')"),'demand signals must stay under AI-STAGING table prefix');
const cutoverDemandSource=await read('canonical-cutover.js');
assert(cutoverDemandSource.includes('client.saveDemand(post.id'),'demand evidence write UI missing');
assert(cutoverDemandSource.includes('購入予約や決済ではなく'),'demand evidence must distinguish signal from purchase');
assert(cutoverDemandSource.includes('source_author'),'source-author exclusion UI path missing');
const contributionSource=await read('voice-contribution-history.js');
assert(contributionSource.includes('client.listMyVoiceHistory()'),'Voice Contribution History canonical read missing');
const cutoverRoleSource=await read('canonical-cutover.js');
assert(cutoverRoleSource.includes('participant_role:selectedRole'),'thread participant role persistence missing');
const threadHistorySource=await read('supabase/functions/ai-staging-boyaki-thread-api/index.ts');
assert(threadHistorySource.includes("path==='/me/voice-history'"),'Voice history endpoint missing');
assert(threadHistorySource.includes(".eq('participant_role','voice')"),'Voice history role filter missing');
const apiSource=await read('supabase/functions/ai-staging-boyaki-api/index.ts');
assert(apiSource.includes("db.from('boyaki_accounts').select('account_pubkey')"),'shared identity read missing');
assert(!/db\.from\('boyaki_accounts'\)\.(?:insert|upsert|update|delete)/.test(apiSource),'AI-STAGING must never mutate shared identity');
assert(apiSource.includes("activity_scope:'AI-STAGING'"),'activity scope marker missing');
console.log(JSON.stringify({ok:true,checks:['local/session sentinel preserved including clear','normal APIs blocked except exact read-only shared identity resolver','Production API and path traversal denied before transport','public WebSockets blocked','worker cleanup limited to AI prefix','worker ignores API and other environments','all live HTML has early boundary and CSP','all application storage scoped','AI backend may read shared identity but cannot mutate it','AI activity remains explicitly scoped to AI-STAGING','Solution Room uses isolated API rather than public relays','Solution Room storage stays under ai_staging_*','Thread -> Room transition is canonical','Solution Cases are account-scoped and not browser-only','Demand Evidence stays under ai_staging_* and is not framed as purchase','Voice role is persisted and Voice history is account-scoped','relative assets exist'],files:files.length},null,2));
