import { createClient } from 'npm:@supabase/supabase-js@2';
import { verifyEvent } from 'npm:nostr-tools@2.17.0';
import { sha256HexText, verifyNostrHttpAuth, type NostrHttpAuthEvent } from '../_shared/nostr-http-auth.ts';

type Json = Record<string, unknown>;
const SUPABASE_URL=Deno.env.get('SUPABASE_URL')||'';
const SERVICE_ROLE_KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const MODERATOR_TOKEN=Deno.env.get('BOYAKI_MODERATOR_TOKEN')||'';
const supabase=createClient(SUPABASE_URL,SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});

function cors(req:Request):HeadersInit{const origin=req.headers.get('origin')||'';const ok=origin==='https://camembert1001.github.io'||/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/.test(origin);return{...(ok?{'Access-Control-Allow-Origin':origin}:{}),'Access-Control-Allow-Headers':'authorization, content-type, x-boyaki-moderator-token','Access-Control-Allow-Methods':'GET,POST,DELETE,OPTIONS','Vary':'Origin'}}
function json(req:Request,status:number,body:Json|Json[]){return new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json; charset=utf-8',...cors(req)}})}
function pathOf(url:URL){const marker='/boyaki-api';const i=url.pathname.indexOf(marker);if(i<0)return url.pathname||'/';return url.pathname.slice(i+marker.length)||'/'}
function tag(ev:any,name:string){return ev?.tags?.find((t:unknown[])=>t?.[0]===name)?.[1] as string|undefined}
function isHex64(v:unknown):v is string{return typeof v==='string'&&/^[0-9a-f]{64}$/.test(v)}
function isUuid(v:string){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v)}
async function rawBody(req:Request){const t=await req.text();if(t.length>32000)throw new Error('request_body_too_large');return t}
function parse(raw:string){if(!raw)return{};try{return JSON.parse(raw)}catch{throw new Error('invalid_json')}}
async function consume(ev:NostrHttpAuthEvent,req:Request){const{error}=await supabase.from('boyaki_request_receipts').insert({auth_event_id:ev.id,actor_pubkey:ev.pubkey,method:req.method.toUpperCase(),request_url:req.url});if(!error)return;if((error as any).code==='23505')throw new Error('replayed_signed_request');throw new Error(`request_receipt_failed:${error.message}`)}
async function audit(kind:string,id:string|null,action:string,targetType:string,targetId:string,metadata:Json={}){const{error}=await supabase.from('boyaki_audit_log').insert({actor_kind:kind,actor_id:id,action,target_type:targetType,target_id:targetId,metadata});if(error)console.error('audit',error.message)}
async function ensureAccount(pk:string){const{error}=await supabase.from('boyaki_accounts').upsert({account_pubkey:pk},{onConflict:'account_pubkey'});if(error)throw new Error(`account_upsert_failed:${error.message}`)}
async function linkedAccount(legacy:string){const{data,error}=await supabase.from('boyaki_identity_links').select('account_pubkey').eq('legacy_pubkey',legacy).eq('status','verified').maybeSingle();if(error)throw new Error(`identity_link_lookup_failed:${error.message}`);return data?.account_pubkey||null}
async function ownerFor(pk:string,kind:string){if(kind==='account'){await ensureAccount(pk);return pk}if(kind!=='legacy_browser')throw new Error('invalid_identity_kind');return linkedAccount(pk)}
function requireModerator(req:Request){if(!MODERATOR_TOKEN)throw new Error('moderator_not_configured');if((req.headers.get('x-boyaki-moderator-token')||'')!==MODERATOR_TOKEN)throw new Error('moderator_unauthorized')}
function validateLink(claim:any,accept:any){if(!claim||!accept||!verifyEvent(claim)||!verifyEvent(accept))throw new Error('invalid_link_signature');if(claim.kind!==30078||accept.kind!==30078)throw new Error('invalid_link_kind');if(tag(claim,'schema')!=='boyaki-account-link-v1'||tag(accept,'schema')!=='boyaki-account-link-v1')throw new Error('invalid_link_schema');const account=tag(claim,'account'),legacy=tag(claim,'legacy');if(!isHex64(account)||!isHex64(legacy))throw new Error('invalid_link_identity');if(tag(accept,'account')!==account||tag(accept,'legacy')!==legacy)throw new Error('link_pair_mismatch');if(claim.pubkey!==legacy||tag(claim,'direction')!=='legacy-claims-account')throw new Error('invalid_legacy_claim');if(accept.pubkey!==account||tag(accept,'direction')!=='account-accepts-legacy')throw new Error('invalid_account_acceptance');return{account,legacy}}


function validCredentialEnvelope(v:unknown):v is string{return typeof v==='string'&&v.startsWith('ncryptsec1')&&v.length>=80&&v.length<=2048}
async function resolveCredential(req:Request,url:URL){
  const hash=(url.searchParams.get('login_key_hash')||'').trim().toLowerCase();
  if(!isHex64(hash))return json(req,400,{error:'invalid_login_key_hash'});
  const{data,error}=await supabase.from('boyaki_account_credentials').select('account_pubkey,encrypted_secret,credential_version').eq('login_key_hash',hash).maybeSingle();
  if(error)throw new Error(`credential_lookup_failed:${error.message}`);
  if(!data)return json(req,404,{error:'credential_not_found'});
  return json(req,200,{account_pubkey:data.account_pubkey,encrypted_secret:data.encrypted_secret,credential_version:data.credential_version});
}
async function saveCredential(req:Request,raw:string){
  const auth=await verifyNostrHttpAuth(req,raw,{requirePayload:true});await consume(auth,req);
  const body=parse(raw),hash=typeof body.login_key_hash==='string'?body.login_key_hash.trim().toLowerCase():'',encrypted=body.encrypted_secret;
  if(!isHex64(hash))return json(req,400,{error:'invalid_login_key_hash'});
  if(!validCredentialEnvelope(encrypted))return json(req,400,{error:'invalid_encrypted_secret'});
  await ensureAccount(auth.pubkey);
  const{data:byAccount,error:aerr}=await supabase.from('boyaki_account_credentials').select('account_pubkey,login_key_hash,credential_version').eq('account_pubkey',auth.pubkey).maybeSingle();
  if(aerr)throw new Error(`credential_account_lookup_failed:${aerr.message}`);
  if(byAccount&&byAccount.login_key_hash!==hash)return json(req,409,{error:'stable_login_key_mismatch'});
  const{data:byHash,error:herr}=await supabase.from('boyaki_account_credentials').select('account_pubkey').eq('login_key_hash',hash).maybeSingle();
  if(herr)throw new Error(`credential_hash_lookup_failed:${herr.message}`);
  if(byHash&&byHash.account_pubkey!==auth.pubkey)return json(req,409,{error:'login_key_already_bound'});
  const version=(byAccount?.credential_version||0)+1,now=new Date().toISOString();
  const{error}=await supabase.from('boyaki_account_credentials').upsert({account_pubkey:auth.pubkey,login_key_hash:hash,encrypted_secret:encrypted,credential_version:version,updated_at:now},{onConflict:'account_pubkey'});
  if(error)throw new Error(`credential_upsert_failed:${error.message}`);
  await audit('account',auth.pubkey,byAccount?'account.password.reset':'account.credential.register','account',auth.pubkey,{credential_version:version});
  return json(req,200,{ok:true,account_pubkey:auth.pubkey,credential_version:version,stable_login_key:true});
}

async function createPost(req:Request,raw:string){const auth=await verifyNostrHttpAuth(req,raw,{requirePayload:true});await consume(auth,req);const body=parse(raw),content=typeof body.content==='string'?body.content.trim():'',kind=body.identity_kind;if(!content||content.length>2000)return json(req,400,{error:'invalid_content'});if(kind!=='account'&&kind!=='legacy_browser')return json(req,400,{error:'invalid_identity_kind'});const owner=await ownerFor(auth.pubkey,kind),commitment=await sha256HexText(content);const{data,error}=await supabase.from('boyaki_posts').insert({author_pubkey:auth.pubkey,author_identity_kind:kind,owner_account_pubkey:owner,content,content_commitment:commitment,status:'active'}).select('id,author_pubkey,owner_account_pubkey,content,status,created_at').single();if(error)throw new Error(`post_insert_failed:${error.message}`);await audit(kind,auth.pubkey,'post.create','post',data.id,{owner_account_pubkey:owner});return json(req,201,{post:data})}
async function listPosts(req:Request,url:URL){const n=Math.max(1,Math.min(Number(url.searchParams.get('limit')||50)||50,100));const{data,error}=await supabase.from('boyaki_posts').select('id,author_pubkey,content,created_at,status').eq('status','active').order('created_at',{ascending:false}).limit(n);if(error)throw new Error(`post_list_failed:${error.message}`);return json(req,200,{posts:data||[]})}
async function listMine(req:Request){const auth=await verifyNostrHttpAuth(req,'',{requirePayload:false});const linked=await linkedAccount(auth.pubkey),account=linked||auth.pubkey;const{data,error}=await supabase.from('boyaki_posts').select('id,author_pubkey,owner_account_pubkey,content,status,created_at,withdrawn_at,moderated_at,deleted_at').or(`owner_account_pubkey.eq.${account},author_pubkey.eq.${auth.pubkey}`).order('created_at',{ascending:false}).limit(500);if(error)throw new Error(`mine_list_failed:${error.message}`);return json(req,200,{account_pubkey:account,posts:data||[]})}
async function deletePost(req:Request,id:string){if(!isUuid(id))return json(req,400,{error:'invalid_post_id'});const auth=await verifyNostrHttpAuth(req,'',{requirePayload:false});await consume(auth,req);const{data:post,error}=await supabase.from('boyaki_posts').select('id,author_pubkey,author_identity_kind,owner_account_pubkey').eq('id',id).maybeSingle();if(error)throw new Error(`post_lookup_failed:${error.message}`);if(!post)return json(req,404,{error:'post_not_found'});if(post.author_pubkey!==auth.pubkey&&post.owner_account_pubkey!==auth.pubkey)return json(req,403,{error:'not_post_owner'});const now=new Date().toISOString();const{error:uerr}=await supabase.from('boyaki_posts').update({content:null,status:'deleted',withdrawn_at:now,deleted_at:now}).eq('id',id);if(uerr)throw new Error(`post_delete_failed:${uerr.message}`);await audit(post.owner_account_pubkey===auth.pubkey?'account':post.author_identity_kind,auth.pubkey,'post.delete','post',id);return json(req,200,{ok:true,id,status:'deleted'})}
async function verifyLink(req:Request,raw:string){const body=parse(raw),{account,legacy}=validateLink(body.legacy_claim,body.account_acceptance);const{data:existing,error:e}=await supabase.from('boyaki_identity_links').select('account_pubkey,status').eq('legacy_pubkey',legacy).maybeSingle();if(e)throw new Error(`identity_link_lookup_failed:${e.message}`);if(existing?.status==='verified'&&existing.account_pubkey!==account)return json(req,409,{error:'legacy_already_linked_to_another_account'});await ensureAccount(account);const{error}=await supabase.from('boyaki_identity_links').upsert({account_pubkey:account,legacy_pubkey:legacy,status:'verified',legacy_claim_event_id:body.legacy_claim.id,account_accept_event_id:body.account_acceptance.id,verified_at:new Date().toISOString(),revoked_at:null},{onConflict:'account_pubkey,legacy_pubkey'});if(error)throw new Error(`identity_link_upsert_failed:${error.message}`);for(const result of await Promise.all([supabase.from('boyaki_posts').update({owner_account_pubkey:account}).eq('author_pubkey',legacy).is('owner_account_pubkey',null),supabase.from('boyaki_legacy_controls').update({owner_account_pubkey:account}).eq('author_pubkey',legacy).is('owner_account_pubkey',null),supabase.from('boyaki_contribution_evidence').update({actor_account_pubkey:account}).eq('actor_legacy_pubkey',legacy).is('actor_account_pubkey',null)])){if(result.error)throw new Error(`identity_backfill_failed:${result.error.message}`)}await audit('system',null,'identity.link.verify','legacy_identity',legacy,{account_pubkey:account});return json(req,200,{ok:true,account_pubkey:account,legacy_pubkey:legacy})}
async function registerLegacy(req:Request,raw:string){const auth=await verifyNostrHttpAuth(req,raw,{requirePayload:true});await consume(auth,req);const body=parse(raw),ev=body.nostr_event;if(!ev||!verifyEvent(ev))return json(req,400,{error:'invalid_legacy_event_signature'});if(ev.kind!==1||tag(ev,'t')!=='boyaki-raw'||!isHex64(ev.id)||!isHex64(ev.pubkey))return json(req,400,{error:'invalid_legacy_event'});const owner=await linkedAccount(ev.pubkey);if(auth.pubkey!==ev.pubkey&&auth.pubkey!==owner)return json(req,403,{error:'not_legacy_owner'});const{error}=await supabase.from('boyaki_legacy_controls').upsert({nostr_event_id:ev.id,author_pubkey:ev.pubkey,owner_account_pubkey:owner,status:'active'},{onConflict:'nostr_event_id',ignoreDuplicates:true});if(error)throw new Error(`legacy_control_upsert_failed:${error.message}`);return json(req,200,{ok:true,nostr_event_id:ev.id,owner_account_pubkey:owner})}
async function legacyStates(req:Request,url:URL){const ids=(url.searchParams.get('ids')||'').split(',').map(x=>x.trim()).filter(isHex64).slice(0,200);if(!ids.length)return json(req,200,{controls:[]});const{data,error}=await supabase.from('boyaki_legacy_controls').select('nostr_event_id,status,owner_account_pubkey').in('nostr_event_id',ids);if(error)throw new Error(`legacy_control_list_failed:${error.message}`);return json(req,200,{controls:data||[]})}
async function deleteLegacy(req:Request,id:string){if(!isHex64(id))return json(req,400,{error:'invalid_legacy_event_id'});const auth=await verifyNostrHttpAuth(req,'',{requirePayload:false});await consume(auth,req);const{data:c,error}=await supabase.from('boyaki_legacy_controls').select('author_pubkey,owner_account_pubkey').eq('nostr_event_id',id).maybeSingle();if(error)throw new Error(`legacy_control_lookup_failed:${error.message}`);if(!c)return json(req,404,{error:'legacy_control_not_registered'});if(c.author_pubkey!==auth.pubkey&&c.owner_account_pubkey!==auth.pubkey)return json(req,403,{error:'not_legacy_owner'});const{error:u}=await supabase.from('boyaki_legacy_controls').update({status:'withdrawn',withdrawn_at:new Date().toISOString()}).eq('nostr_event_id',id);if(u)throw new Error(`legacy_withdraw_failed:${u.message}`);return json(req,200,{ok:true,nostr_event_id:id,status:'withdrawn',relay_erasure_guaranteed:false})}
async function report(req:Request,raw:string){const auth=await verifyNostrHttpAuth(req,raw,{requirePayload:true});await consume(auth,req);const body=parse(raw),type=body.target_type,id=body.target_id,reason=typeof body.reason_code==='string'?body.reason_code.slice(0,80):'other',detail=typeof body.detail==='string'?body.detail.trim().slice(0,1000):null;let row:any;if(type==='post'&&typeof id==='string'&&isUuid(id))row={post_id:id,legacy_nostr_event_id:null};else if(type==='legacy'&&isHex64(id))row={post_id:null,legacy_nostr_event_id:id};else return json(req,400,{error:'invalid_report_target'});const{data,error}=await supabase.from('boyaki_reports').insert({...row,reporter_pubkey:auth.pubkey,reason_code:reason,detail,status:'open'}).select('id').single();if(error)throw new Error(`report_insert_failed:${error.message}`);return json(req,201,{ok:true,report_id:data.id})}
async function moderation(req:Request,raw:string){requireModerator(req);const body=parse(raw),type=body.target_type,id=body.target_id,action=body.action,reason=typeof body.reason_code==='string'?body.reason_code.slice(0,80):'other';if(!['hide','restore','purge'].includes(action))return json(req,400,{error:'invalid_moderation_action'});const now=new Date().toISOString();let actionRow:any;if(type==='post'&&typeof id==='string'&&isUuid(id)){if(action==='restore'){const{data}=await supabase.from('boyaki_posts').select('content').eq('id',id).maybeSingle();if(!data?.content)return json(req,409,{error:'purged_content_cannot_be_restored'})}const patch=action==='restore'?{status:'active',moderated_at:null}:action==='purge'?{status:'deleted',content:null,moderated_at:now,deleted_at:now}:{status:'moderated',moderated_at:now};const{error}=await supabase.from('boyaki_posts').update(patch).eq('id',id);if(error)throw new Error(`moderation_post_update_failed:${error.message}`);actionRow={post_id:id,legacy_nostr_event_id:null}}else if(type==='legacy'&&isHex64(id)){const patch=action==='restore'?{status:'active',moderated_at:null}:{status:'moderated',moderated_at:now};const{error}=await supabase.from('boyaki_legacy_controls').update(patch).eq('nostr_event_id',id);if(error)throw new Error(`moderation_legacy_update_failed:${error.message}`);actionRow={post_id:null,legacy_nostr_event_id:id}}else return json(req,400,{error:'invalid_moderation_target'});const{error}=await supabase.from('boyaki_moderation_actions').insert({...actionRow,moderator_actor:'operator',action,reason_code:reason});if(error)throw new Error(`moderation_log_failed:${error.message}`);return json(req,200,{ok:true,target_type:type,target_id:id,action})}

Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});if(!SUPABASE_URL||!SERVICE_ROLE_KEY)return json(req,503,{error:'canonical_backend_not_configured'});const url=new URL(req.url),path=pathOf(url);try{if(req.method==='GET'&&path==='/health')return json(req,200,{ok:true,service:'boyaki-api',canonical_storage:true,password_reset:true,version:'staging-v4'});if(req.method==='GET'&&path==='/account-credentials/resolve')return resolveCredential(req,url);if(req.method==='GET'&&path==='/posts')return listPosts(req,url);if(req.method==='GET'&&path==='/me/posts')return listMine(req);if(req.method==='GET'&&path==='/legacy-controls')return legacyStates(req,url);if(req.method==='GET'&&path==='/moderation/reports'){requireModerator(req);const{data,error}=await supabase.from('boyaki_reports').select('*').eq('status','open').order('created_at',{ascending:false}).limit(500);if(error)throw error;return json(req,200,{reports:data||[]})}if(req.method==='GET'&&path==='/moderation/posts'){requireModerator(req);const{data,error}=await supabase.from('boyaki_posts').select('id,author_pubkey,owner_account_pubkey,content,status,created_at,withdrawn_at,moderated_at,deleted_at').order('created_at',{ascending:false}).limit(500);if(error)throw error;return json(req,200,{posts:data||[]})}const raw=await rawBody(req);if(req.method==='POST'&&path==='/account-credentials')return saveCredential(req,raw);if(req.method==='POST'&&path==='/posts')return createPost(req,raw);if(req.method==='POST'&&path==='/identity-links/verify')return verifyLink(req,raw);if(req.method==='POST'&&path==='/legacy-controls/register')return registerLegacy(req,raw);if(req.method==='POST'&&path==='/reports')return report(req,raw);if(req.method==='POST'&&path==='/moderation')return moderation(req,raw);const pd=/^\/posts\/([0-9a-f-]+)$/i.exec(path);if(req.method==='DELETE'&&pd)return deletePost(req,pd[1]);const ld=/^\/legacy\/([0-9a-f]{64})$/i.exec(path);if(req.method==='DELETE'&&ld)return deleteLegacy(req,ld[1]);return json(req,404,{error:'not_found'})}catch(err){const message=err instanceof Error?err.message:String(err);console.error('boyaki-api',message);const unauthorized=/authorization|signature|stale|replayed|moderator_unauthorized/.test(message),unavailable=/not_configured/.test(message);return json(req,unavailable?503:unauthorized?401:500,{error:message})}});